theme = "catppuccin_frappe"

[editor]
line-number = "relative"
true-color = true
color-modes = true
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["position", "file-encoding", "file-type", "version-control"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
C-s = ":w"
C-x = ":buffer-close"
C-q = ":q"

[keys.normal."backspace"]
s = [":w", ":config-reload"]
c = ":config-open"
t = ":open ~/.config/tmux/tmux.conf"
"1" = ":theme dracula"
"2" = ":theme github_light"
