[[language]]
name = "c-sharp"
auto-format = true

[[language]]
name = "rust"
formatter = { command = "rustfmt" }
auto-format = true
file-types = ["rs"]

[language-server.rust-analyzer.config]
checkOnSave = { command = "clippy", extraArgs = ["--", "-W", "clippy::pedantic"] }
cargo = { allFeatures = true }

